### ISSUE TITLE
What is the version of the original code?

### ISSUE THREAD

**Issue by leiqunni** [dgileadi/CsPieceTree#1]
I want to take the difference and catch up with the latest version.
Also, UTF16Array and UTF32Array are int arrays, but can they be char[]?

**Comment by dgileadi** [comment]
I don't have an easy link I can point to, but the code was whatever version was available on the `main` branch at https://github.com/microsoft/vscode/tree/main/src/vs/editor/common/model/pieceTreeTextBuffer in early July of 2021.

Unfortunately I'm not maintaining this repo (I found I didn't need it after all) so I don't plan to change the code. Feel free to fork it, though!
